docs/design/3-support-service-init-via-config-string.md

ref: https://github.com/Xuanwo/storage/issues/37

docs/design: Add draft for support service init via config string

---

docs/design/11-error-handling.md
docs/design/3-support-service-init-via-config-string.md
docs/design/4-credential-refactor.md
docs/design/9-remove-storager-init.md
docs/spec/1-error-handling.md

docs/{design,spec}: Add proposal for error handling

---

docs/_sidebar.md
index.html

docs: Use docsify to build docs

---

docs/_sidebar.md

docs: Update sidebar

---

services/azblob/generated.go
services/azblob/servicer.go
services/azblob/storager.go
services/azblob/utils.go
services/qingstor/servicer.go

services/azblob: Implement proposal 11-error-handling

---

services/cos/generated.go
services/cos/servicer.go
services/cos/storager.go
services/cos/utils.go

services/cos: Implement proposal 11-error-handling

---

services/dropbox/storager.go

services/dropbox: Implement proposal 11-error-handling

---

services/gcs/generated.go
services/gcs/servicer.go
services/gcs/storager.go
services/gcs/utils.go

services/gcs: Implement proposal 11-error-handling

---

services/kodo/generated.go
services/kodo/servicer.go
services/kodo/storager.go
services/kodo/utils.go

services/kodo: Implement proposal 11-error-handling

---

services/oss/generated.go
services/oss/servicer.go
services/oss/storager.go
services/oss/utils.go

services/oss: Implement proposal 11-error-handling

---

README.md

docs: Add telegram link in README

---

services/s3/generated.go
services/s3/servicer.go
services/s3/storager.go
services/s3/utils.go

services/s3: Implement proposal 11-error-handling

---

services/uss/storager.go
services/uss/utils.go

services/uss: Implement proposal 11-error-handling

---

docs/design/12-support-both-directory-and-prefix-based-list.md
docs/design/2-use-callback-in-list-operations.md

docs/design: Support both directory and prefix based list

---

services/gcs/storager.go
services/kodo/storager.go
services/oss/storager.go
services/s3/storager.go

services/{gcs,kodo,oss,s3}: Fix Object type in List incorrect

---

internal/cmd/service/meta.go
services/qingstor/generated.go
services/qingstor/storager.go

services/*: Add ReadCallbackFunc for WriteSegment

---

services/fs/storager.go

services/fs: Fix size and offset pair not handled correctly

---

services/cos/servicer.go
services/cos/storager.go
services/cos/utils.go

services/cos: Refactor service newStorage

---

services/kodo/storager.go

services/kodo: Fix ID not set

---

CHANGELOG.md
docs/design/10/go.sum
go.mod
go.sum
tests/go.sum

Bump to version v0.8.0

---

docs/design/15-release-policy.md

docs/design: Add proposal release policy

---

docs/design/14-normalize-content-hash-check.md
docs/design/15-release-policy.md
docs/design/16-loose-mode.md

docs/design: Add proposal loose mode

---

docs/design/17-proposal-process.md
docs/spec/2-proposal.md

docs: Add proposal 17-proposal-process

---

services/qingstor/generated.go
services/qingstor/storager.go
services/s3/generated.go
services/s3/meta.json
services/s3/storager.go

services/s3: Add multipart support

---

services/qingstor/constants.go
services/qingstor/storager.go

services/qingstor: Dir support is not needed in stat

---

services/azblob/utils.go
services/cos/utils.go
services/kodo/utils.go
services/oss/utils.go
services/s3/utils.go
services/uss/utils.go

services/*: Fix error not handled correctly with empty body

---

docs/design/10/go.sum
go.mod
go.sum
services/qingstor/servicer.go
tests/go.sum

services/qingstor: Fix ListBuckets incomplete

---

services/azblob/generated.go
services/azblob/meta.json
services/azblob/storager.go

services/azblob: Add offset and size support for Read

---

services/azblob/servicer.go
services/azblob/storager.go
services/cos/servicer.go
services/cos/storager.go
services/dropbox/storager.go
services/dropbox/utils.go
services/fs/utils.go
services/gcs/servicer.go
services/gcs/storager.go
services/kodo/servicer.go
services/kodo/storager.go
services/oss/servicer.go
services/oss/storager.go
services/qingstor/servicer.go
services/qingstor/storager.go
services/s3/servicer.go
services/s3/storager.go
services/uss/storager.go
services/uss/utils.go
storager.go
types/pairs/pairs.go
types/pairs/pairs.json

services/*: Fix getAbsPath and getRelPath not handled correctly

---

tests/storager.yaml.example
tests/storager_test.go

tests: Refactor integration test

---

services/azblob/storager.go
services/azblob/utils.go

services/azblob: Fix context deadline exceeded while reading

---

services/qingstor/generated.go
services/qingstor/meta.json
services/qingstor/servicer.go

services/qingstor: Detect bucket location automatically

---

docs/.vuepress/config.js
docs/package.json
docs/yarn.lock

docs: Import user experience

---

docs/.vuepress/config.js
docs/README.md

docs: Get ready for i18n docs

---

definitions/services/azblob.hcl
definitions/services/cos.hcl
definitions/services/dropbox.hcl
definitions/services/gcs.hcl
definitions/services/kodo.hcl
definitions/services/oss.hcl
definitions/services/qingstor.hcl
definitions/services/s3.hcl
definitions/services/uss.hcl
internal/cmd/definitions/parse.go
internal/cmd/definitions/type.go
services/azblob/generated.go
services/cos/generated.go
services/dropbox/generated.go
services/gcs/generated.go
services/kodo/generated.go
services/oss/generated.go
services/qingstor/generated.go
services/s3/generated.go
services/uss/generated.go

definitions: Auto inject http_client_options for all services

---

services/fs/utils.go

services/fs: Auto create work dir

---

pkg/iowrap/reader.go
pkg/iowrap/reader_test.go

pkg/iowrap: Add SizedReadSeekCloser support

---

services/azblob/storager.go

services/azblob: Fix content length not set correctly

---

.drone.yml

tests: Add integration test for azblob

---

services/s3/utils.go

services/s3: Fix NotFound error not handled correctly

---

services/s3/storager.go

services/s3: Fix ListDir && ListPrefix not ended correctly

---

services/s3/storager.go

services/s3: Fix Read's pair not parsed correctly

---

services/s3/storager.go

services/s3: Fix bucket in request input not assigned

---

definitions/services/s3.hcl
services/s3/generated.go
services/s3/servicer.go
services/s3/storager.go
services/s3/utils.go

services/s3: Location should be required in Storager Init

---

services/s3/servicer.go
services/s3/storager.go
services/s3/utils.go

services/s3: Don't calculate content-sha256 as default

---

.drone.yml

tests: Add integration test for s3

---

services/gcs/storager.go

services/gcs: Fix ListDir and ListPrefix not ended correctly

---

go.mod
pkg/credential/credential.go
pkg/credential/credential_test.go
services/gcs/utils.go
tests/storager_test.go

services/gcs: Fix oauth2 token source not configured correctly

---

.drone.yml

tests: Add integration test for oss

---

pkg/endpoint/endpoint.go
pkg/endpoint/endpoint_test.go

pkg/endpoint: Allow omit protocol default port

---

.drone.yml

tests: Add integration test for kodo

---

README.md
docs/README.md
docs/services/README.md
docs/services/azblob.md
docs/services/cos.md
docs/services/fs.md
docs/services/gcs.md
docs/services/kodo.md
docs/services/oss.md
docs/services/qingstor.md
docs/services/s3.md
docs/services/uss.md
types/struct.go

docs: Update README and services related docs

---

CHANGELOG.md
docs/zh-CN/README.md
docs/zh-CN/services/README.md
docs/zh-CN/services/azblob.md
docs/zh-CN/services/cos.md
docs/zh-CN/services/fs.md
docs/zh-CN/services/gcs.md
docs/zh-CN/services/kodo.md
docs/zh-CN/services/oss.md
docs/zh-CN/services/qingstor.md
docs/zh-CN/services/s3.md
docs/zh-CN/services/uss.md
go.mod
go.sum
tests/go.sum

Bump version to 1.2.0

---

services/qingstor/storage.go
services/qingstor/storager_test.go
services/qingstor/utils.go
services/qingstor/utils_test.go

services/qingstor: Fix WorkDir listed in keys while ListDir 

---

definitions/operations.hcl
definitions/services/qingstor.hcl
generated.go
services/qingstor/generated.go
services/qingstor/storage.go

definitions: Fix statistical's result is incorrect

---

services/qingstor/storager_test.go

services/qingstor: Fix unit test for ListDir

---

README.md

docs: Migrate chat to zulip

---

cmd/definitions/go.mod

cmd/definitions: Submodules should not contain major version

---

.github/workflows/unittest.yml
cmd/definitions/go.mod
go.mod
internal/cmd/go.mod

*: Improve minimum supported version to go 1.14

---

pkg/endpoint/endpoint_test.go

pkg/endpoint: Underlying error supports xerrors.Wrapper for now

---

README.md
doc.go

docs: Update README

---

CHANGELOG.md
go.mod
go.sum

Bump version to 2.0.0-alpha.1

---

.github/workflows/automerge.yml

ci: Add automerge support

---

pkg/storageclass/storageclass.go

pkg/storageclass: Add storageclass support

---

.github/workflows/automerge.yml

ci: Remove the require of lgtm label

---

CHANGELOG.md

Bump to version 2.0.0-beta

---

Makefile
cmd/definitions/format.go
cmd/definitions/generate.go
cmd/definitions/main.go
cmd/definitions/parse.go
cmd/definitions/spec.go
cmd/definitions/tools.go
cmd/definitions/type.go
doc.go
internal/cmd/go.mod
internal/cmd/iterator/main.go

cmd: Add tools tag into build

---

CHANGELOG.md

Bump to version 2.0.0

---

types/object.go
types/object_test.go

types: Implement Stringer for ObjectMode

---

CHANGELOG.md

Bump to version 3.3.0

---

go.mod
go.sum
types/operation.generated.go

storage: Rename New to Create

---

CHANGELOG.md

Bump to version 3.4.0

---

CHANGELOG.md

Bump to version 3.4.1

---

go.mod
go.sum
types/object.generated.go

Signed-off-by: Prnyself <281239768@qq.com>

object: Add Multipart related fields into object

---

CHANGELOG.md

Signed-off-by: Prnyself <281239768@qq.com>

Bump to version 3.4.2

---

cmd/definitions/type.go

cmd/definitions: Increase stablility of generated code

---

pkg/iowrap/doc.go
pkg/iowrap/interface.go
pkg/iowrap/pipe.go
pkg/iowrap/reader.go
pkg/iowrap/writer.go

pkg/iowrap: Add ReadAtCloser

---

CHANGELOG.md

Bump to version 3.5.0 to close #527 .

Bump to version 3.5.0

---

CHANGELOG.md
README.md

Bump to version 3.6.0

---

go.mod
go.sum
types/object.generated.go
types/operation.generated.go

storage: Implement AOS-44

---

go.mod
go.sum
types/operation.generated.go

storage: Implement AOS-49 Add CreateDir Operation

---

go.mod
go.sum
services/error.go

https://github.com/aos-dev/specs/pull/51

Implement AOS-51: Distinguish Errors by IsAosError

---

cmd/definitions/tests/doc.go

Signed-off-by: Prnyself <281239768@qq.com>

docs: Add comment to illustrate ignoring generated.go in tests package

---

types/object.go
types/object_test.go

Add functions `Add` and `Del` for `ObjectMode`.

Add functions Add and Del for ObjectMode

---

cmd/definitions/bindata.go
pkg/iowrap/reader.go

iowrap: Explicit declare implemented interface

---

cmd/definitions/tests/storage.go
go.mod
go.sum
types/operation.generated.go

Implement GSP-76 Local Function Metadata (#77)

---

types/error.go
types/iterator.go
types/operation.go

types: Fix IterateDone doesn't implement InternalError

---

cmd/definitions/tests/service.toml
cmd/definitions/type.go
go.mod
go.sum
pairs/generated.go
types/operation.generated.go

cmd/definitions: Implement GSP-93 Add ObjectMode Pair

---

CHANGELOG.md

Bump to version 4.1.0

---

pkg/endpoint/endpoint.go
pkg/endpoint/error.go

pkg/endpoint: Refactor with provider

---

README.md

docs: Reorganize README for better understanding

---

cmd/definitions/parse.go
pkg/fswrap/iofs.go
services/new.go

https://github.com/beyondstorage/go-service-ipfs/pull/3#commitcomment-53044856

definitions: Add support for type uint64

---

services/error.go

services: Implement GSP-127: Add ServiceInternal and RequestThrottled Errors

---

docs/rfcs/0-example.md

Update RFC template

---

Makefile
cmd/definitions/bindata/bindata.go
cmd/definitions/parse.go
cmd/definitions/tools.go
cmd/definitions/type.go

makefile: Fix code not formatted correctly

---

CHANGELOG.md

ref: https://github.com/beyondstorage/go-storage/issues/663

Bump to version 4.3.0

---

pkg/endpoint/endpoint.go
pkg/endpoint/endpoint_test.go
pkg/endpoint/error.go

ref: https://github.com/beyondstorage/go-storage/issues/666

fix: Add pkg/endpoint back to avoid breaking other projects

---

CHANGELOG.md

Bump to version 4.3.2

---

tests/storage.go
tests/storager_bench_test.go

tests: Implement bench for List

---

README.md

ref: https://github.com/beyondstorage/community/issues/29

docs: Update links to matrix

---

cmd/definitions/bindata/bindata.go
cmd/definitions/generate.go
cmd/definitions/main.go
cmd/definitions/specs/build.go
cmd/definitions/specs/build_test.go
cmd/definitions/specs/parse.go
cmd/definitions/specs/spec.go
cmd/definitions/tools.go
cmd/definitions/type.go
internal/cmd/iterator/main.go
services/error.go
services/new.go

feat: Allow append pairs for  New{Servicer,Storager}FromString

---

.github/workflows/cross-build.yml

ci: Add cross build

---

README.md
cmd/definitions/bindata/bindata.go

docs: Add the services bos and obs to the README

docs: Add the services bos and obs to the README

---

cmd/definitions/gen_service.go
tests/generated.go

ref: https://github.com/beyondstorage/go-storage/issues/758

feat: Replace separator with / in path for service

---

cmd/definitions/type.go

fix: Fixed the error when no function is declared under the namespace

---

definitions/features.go
definitions/gen_info.go
definitions/gen_namespace.go
definitions/gen_object.go
definitions/gen_service.go
definitions/infos.go
definitions/namespace.generated.go
definitions/tests/generated_test.go
types/operation.generated.go

feat(definitions): Make sure ListPairs sorted

---

services/s3/storage.go

Update comments for AbortMultipartUpload.
[original issue](https://github.com/beyondstorage/go-storage/issues/963)

services/s3: Update comments for AbortMultipartUpload as its inconsistent behavior

---

definitions/const.go
definitions/gen_service.go
definitions/tests/generated_test.go
definitions/tests/utils_test.go
go.mod
go.sum

feat: Implement Factory

---

.github/workflows/services-test-s3.yml

[Original issue #938](https://github.com/beyondstorage/go-storage/issues/938)

services/s3:Add tests that upon minio

---

definitions/gen_pair.go
definitions/gen_service.go
definitions/metadata.go
definitions/namespace.go
definitions/pairs.go
definitions/tests/generated_test.go
pairs/generated.go

feat: Generate enable feature pairs

---

.github/workflows/README.md
.github/workflows/services-test-azblob.yml
.github/workflows/services-test-azfile.yml
.github/workflows/services-test-bos.yml
.github/workflows/services-test-cos.yml
.github/workflows/services-test-dropbox.yml
.github/workflows/services-test-fs.yml
.github/workflows/services-test-ftp.yml
.github/workflows/services-test-gcs.yml
.github/workflows/services-test-gdrive.yml
.github/workflows/services-test-hdfs.yml
.github/workflows/services-test-ipfs.yml
.github/workflows/services-test-kodo.yml
.github/workflows/services-test-memory.yml
.github/workflows/services-test-minio.yml
.github/workflows/services-test-obs.yml
.github/workflows/services-test-oss.yml
.github/workflows/services-test-qingstor.yml
.github/workflows/services-test-s3.yml
.github/workflows/services-test-storj.yml

chore(ci): Fix service tests not run on master

---

definitions/features.go
definitions/fields.go
definitions/gen_op.go
definitions/gen_service.go
definitions/infos.go
definitions/metadata.go
definitions/namespace.go
definitions/pairs.go
pairs/generated.go
types/operation.generated.go

feat(definitions): Add feature type support

---

definitions/gen_service.go
definitions/tests/generated_test.go

feat(definitions): Add Factory register support

---

definitions/gen_service.go
definitions/tests/conn_test.go
definitions/tests/generated_test.go
services/factory.go

feat(definitions): Fix FromString should trim prefix

---

.github/workflows/services-test-s3.yml
services/s3/tests/utils_test.go

services/s3: Add test upon minio

---

.github/workflows/services-test-minio.yml
services/minio/README.md
services/minio/tests/utils_test.go

change the way of creating bucket.

services/minio: change the way of creating bucket.

---

tests/storager_list.go

fix https://github.com/beyondstorage/go-storage/issues/1034

fix(tests): Create an empty dir for TestListEmptyDir
